#!/bin/sh
wget -O data.zip $1
unzip data.zip -d data
cd data
mv * data
mv data/* .
rm -rf data
mv testA/* trainA/
rm -rf testA
mv testB/* trainB/
rm -rf testB
mv trainA set1
mv trainB set2
cd set1
ls -v | cat -n | while read n f; do mv -n "$f" "$n.jpg"; done 
cd ../set2
ls -v | cat -n | while read n f; do mv -n "$f" "$n.jpg"; done
cd ../..
mkdir decodedArray
mkdir encodedArray
rm -rf data.zip
