pip install tensorflow-gpu==1.15
pip install tensorflow-datasets
pip install glob2 
pip install Pillow
pip install numpy
pip install matplotlib
pip install imageio
pip install tqdm
pip install pathlib